version: "3.3"
services:
  redis_database:
    image: redis:6.2
    container_name: redis
    volumes:
      - ./redis_data:/data
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
      - ./seed/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: autonomous
      MONGO_INITDB_ROOT_PASSWORD: Ftk7N68pUib6LV
volumes:
  mongo-data:
  redis-data:
